/*
 * Be_aware_of_autoGenerated_methods_by_Compiler.hpp
 *
 *  Created on: 2018. 2. 14.
 *      Author: Ciel
 */

#ifndef BE_AWARE_OF_AUTOGENERATED_METHODS_BY_COMPILER_HPP_
#define BE_AWARE_OF_AUTOGENERATED_METHODS_BY_COMPILER_HPP_

#include <iostream>

template <typename T>
class ClassWithExplicitGenerator;

template <typename T>
class ClassWithImplicitGenerator;


#endif /* BE_AWARE_OF_AUTOGENERATED_METHODS_BY_COMPILER_HPP_ */
