# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='PajamaParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('partyAddr', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mvpvote',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloWorld.PajamaParty'),
        ),
    ]
